(define (sum-squares a b) (+ (* a a) (* b b)))
(define (sum-largest-squares a b c) (cond ((and (< a b) (< a c)) (sum-squares b c))
                                          ((< b c) (sum-squares a c))
                                          (else (sum-squares a b))))
(define s sum-largest-squares)
; (sum-largest-squares 1 2 3)
; (sum-largest-squares 1 3 2)
; (sum-largest-squares 2 1 3)
; (sum-largest-squares 2 3 1)
; (sum-largest-squares 3 1 2)
; (sum-largest-squares 3 2 1)
