(define (avg x y)
  (/ (+ x y) 2))
(define (square x) (* x x))
(define (abs x)
  (if (< x 0)
      (- x)
      x))
(define tolerance 0.0000001)
(define (good-enough? guess x) (< (abs (- (square guess)
                                       x))
                                  tolerance))
(define (improve guess x) (avg guess (/ x guess)))
(define (sqrt-iter guess x) (if (good-enough? guess x)
                                guess
                                (sqrt-iter (improve guess x) x)))
(define (my-sqrt x) (sqrt-iter 1.0 x))
